### ISSUE TITLE
인스타그램 / 페이스북 게시글 올리는  API 연동 알아보기

### ISSUE THREAD

**Issue by shinkeonkim** [today-they-learned/peacepiece_api#64]

**Comment by Jihyun-Choi** [comment]
article이 image field가 필수인지 아닌지 프론트와 협의하기 ^~^

**Comment by Jihyun-Choi** [comment]
인스타그램 : 비지니스 계정에 게시물을 예약할 수 있는 API를 만들어놓았지만 비지니스 계정만 가능하며, 하루에 25개의 게시물만 ...? 할 수 있는. ..등. .. ... .여러모론 벤 ........   ....(?)

**Comment by Jihyun-Choi** [comment]
페이스북 : 페이스북 Graph API?를 사용하면 될수도 ... 근데 개인정보 보호 ? 어쩌구 ? 로 인해 검수를 받아햐 하는데 통과 못하면 못씀 + 검수하는데 2~4주 정도 걸림
